### ISSUE TITLE
Improve formatting of result item container

### ISSUE THREAD

**Issue by Samweli** [stac-utils/qgis-stac-plugin#129]
Refactor style and display of the result item widget to give a better highlight of the result item information such as collection name.

Current look of the result item widget, showing an item from Microsoft planetary computer catalog collection
![image](https://user-images.githubusercontent.com/2663775/162965632-ab9fff38-9c41-42ac-8983-6fe4d85b8f12.png)

**Comment by mmcfarland** [comment]
I'm thinking we can use some varying text sizes similar to what the Planetary Computer uses in the Explorer, with some label changes

* Use collection title instead of id, if exists
* Format the date -- and if `start_date` and `end_date` exist, print the range instead of `datetime`
* If eo:cloud_cover exists, put that in the card as well, formatted as percentage

<img height=500 src="https://user-images.githubusercontent.com/1014341/166563139-7445d373-ccf0-4baa-b7e8-6c00303c2374.png"/>
